version: '3.7'
services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prod
    volumes:
      - ./pgdata:/var/lib/postgesql/data
    ports:
      - '5432:5432'
  web:
    image: habitpro
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app